AWSTemplateFormatVersion: 2010-09-09

Description: CloudFront distribution with S3 Origin

Parameters:
  BucketName:
    Type: String
    Description: Unique name for S3 bucket.
  DistributionDescription:
    Type: String
    Description: Description for the CloudFront Distribution

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: 'cloudfront.amazonaws.com'
            Resource: !Sub '${Bucket.Arn}/*'
            Action: 's3:GetObject*'
            Condition:
              StringEquals:
                'AWS:SourceArn': !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}'
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Ref DistributionDescription
        DefaultCacheBehavior: 
          TargetOriginId: !Sub '${Bucket.RegionalDomainName}'
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
          ViewerProtocolPolicy: https-only
        Enabled: 'true'
        HttpVersion: http2
        Origins:
          - DomainName: !GetAtt Bucket.RegionalDomainName
            Id: !GetAtt Bucket.RegionalDomainName
            OriginAccessControlId: !Ref OriginAccessControl
            S3OriginConfig: {}
  OriginAccessControl: 
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Ref BucketName
        Description: !Ref BucketName
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

Outputs:
  CloudFrontDistributionURL:
    Value: !GetAtt CloudFrontDistribution.DomainName